### ISSUE TITLE
Better tutorials (especially for 2D terraria-like worlds)

### ISSUE THREAD

**Issue by Doffilla** [BenjaTK/Gaea#114]
I was trying to make a 2D sandbox like terraria and when I found this I thought it would be a big help. It turned out to be a lot of work just because I couldn't find a good tutorial anywhere. The one that you link to by DevWorm doesn't cover the heightmap one (terraria style) I did figure it out eventually but I think it would help future users and save them a lot of time if you made a better tutorial yourself.

**Comment by rileykot** [comment]
I think, you, @Doffilla, should create a tutorial. It might have been a lot of work to setup and get going, but that still saved you hours and hours of time rather than doing it yourself. The documentation is already really good, you just need to know how to look for it. I think it shouldn't be up to the developer to create tutorials for every use-case that someone may want/need but rather up to people like you who have figured it out for very specific use-cases to contribute to an open source project to support users in the future

**Comment by sethruh** [comment]
@Doffilla, would you be open to explaining how you were able to work it out? i am struggling as well and cant find any of the documents.

**Comment by sethruh** [comment]
@rileykot where exactly are the documents?

**Comment by Doffilla** [comment]
> @Doffilla, would you be open to explaining how you were able to work it out? i am struggling as well and cant find any of the documents.

Well... What's your specific problem?

**Comment by Doffilla** [comment]
> @rileykot where exactly are the documents?

Dunno... Still haven't found any
