### ISSUE TITLE
Autotile Issue

### ISSUE THREAD

**Issue by LunamOdium** [BenjaTK/Gaea#135]
If you have a tileset thats anything but a perfect square, when generating the map there will be a gap between the different tile types(in my case, dirt tile and grass tile) I attempted to generate each on their own layer but it doesnt seem to work at all.

E.g: I have a dirt tile with a threshold of 0.2 to 1 and a grass tile with a threshold of 0.3 to 1. Dirt is layer 0 while grass is layer 1

Theoretically, the dirt should fill the space from 0.2 all the way to 1, and the grass should be drawn ON TOP, from 0.3 to 1, but it does not. 

Either im not understanding how the layers work(as there is no documentation for this) or it simply doesnt work. 

![tilesetTest](https://github.com/BenjaTK/Gaea/assets/82219951/44bc8164-c827-49cb-9a0a-73d082244a55)

**Comment by BenjaTK** [comment]
I'm unable to recreate this, seems to be working fine with me. I think it's because the changes in Godot 4 require a full terrain tileset, one that looks like this:
![image](https://github.com/BenjaTK/Gaea/assets/73806216/cb6d2974-3b09-4758-afa4-97bd075cb0f6)
_(from [Godot 4: Simple Autotile Procedural Generation](https://youtu.be/IPt3jk7IsQw))_
