### ISSUE TITLE
Height-based texturer

### ISSUE THREAD

**Issue by BenjaTK** [BenjaTK/Gaea#6]
(Name needs work)
Basically, what this modifier does is change a tile based on it's height. An example would be: the first tile is a grass tile, the next 3 ones are dirt, then they're stone until the last one, which is bedrock. However, I'm not sure how to implement this since the height can variate between columns. So even though you could set it to look for a certain height, this would just create a straight line. Any help would be appreciated.

**Comment by Nemesis-AS** [comment]
This modifier can generate noises for each junction, and use them to add variation to the tiles.

![image](https://github.com/BenjaTK/Gaea/assets/56386613/f38e25fc-2285-4da0-926d-9446aa4aeacb)
This is the straight line generation I believe you're referring to
The tiles are -> Sky, Grass, Dirt, Stone and Bedrock

![image](https://github.com/BenjaTK/Gaea/assets/56386613/1ea0be1a-541a-491c-838c-6dc3a1ead03c)
I propose we generate a separate noise for each junction of tiles, which are related to the original seed in some way or reproducible results (maybe add 1, 2, 3... for each junction that is present?)
The transparent overlay is the new generated noise, I've used the same one at each junction for simplicity

After that, a simple threshold check can be used to determine if the top tile overflows into the bottom one or vice versa, which would give us something like this
![image](https://github.com/BenjaTK/Gaea/assets/56386613/d9c47496-9bd0-47b0-b6d8-a21c17cfdf1e)

The thresholds could be made tweakable by the user and this modification should be optional as some users may want the straight line generation

I hope I explained the solution I'm proposing properly, and I'm not sure how big of a performance hit this would bring so that needs to be investigated

**Comment by BenjaTK** [comment]
I don't think I'm understanding correctly 😅
What you propose is making noises for the tiles and then generating the terrain from it? Because this modifier would be applied after the terrain was generated.
