### ISSUE TITLE
Optimize _draw_tiles function

### ISSUE THREAD

**Issue by BenjaTK** [BenjaTK/Gaea#7]
HeightmapGenerator2D takes a very long time to generate. Tested with a 1750x900 world, it takes about 25 seconds with no modifiers, and the carver modifier only seems to add only about 2 seconds.

**Comment by Nemesis-AS** [comment]
![image](https://github.com/BenjaTK/Gaea/assets/56386613/40b7d3f3-252d-4a58-a1e2-93c81a28abfb)
This is the result I got when generating a 1750x900 world in the `heightmap_demo` scene. I used `Time.get_ticks_msec()` to measure time

It seems like most of the time is spent on the `_draw_tiles` function, which is hard to optimize any further. I believe chunking can help in this case. It would be easier to draw the terrain in chunks instead of drawing it all at once but the solution may end up adding a slight overhead so it might take longer than 25s(324 in my case) to generate but at least it would be a smoother experience

**Comment by BenjaTK** [comment]
Hi! Thanks for checking it out.
yeah, I suspected it was `_draw_tiles`. It's really slow, ESPECIALLY if you use terrains. I think chunking would be the best solution, but should we add chunking to all generators or just this one? As far as I've seen, they're all pretty slow with a large world size.

**Comment by Nemesis-AS** [comment]
Since all the generators will benefit from chunking, we should add chunking to the `GaeaGenerator` class. And for fine tuning, properties like chunk size could be exposed in the editor

**Comment by BenjaTK** [comment]
Yeah that sounds like the right idea!

**Comment by Salodo** [comment]
I think that the main problem with the drawing is that you are drawing everything at once. Even if its as efficient as possible you are still drawing millions of blocks, I had this problems with my game where the problems isn't the function itself it only took about 0.001 seconds, but rather the amount of times the function needed to happen. I don't know if its possible, but you don't technically have to draw everything at once you could just do it asynchronous by drawing 100 blocks every frame or something. If you unblock the main thread you realise that there was no performance problem in the first place.

**Comment by Nemesis-AS** [comment]
I did give this some thought, but in the end it seems like a chunk system will be implemented anyway so I don't think we need to make any optimization here. But if needed I support moving the tile rendering to another thread

**Comment by BenjaTK** [comment]
That makes sense though! I've never worked with threads so I'll have to look into it but that sounds better than implementing a chunk system for generators that don't need it (I'd prefer chunking to be only used for infinite worlds rather than static ones).

**Comment by BenjaTK** [comment]
Should we close this now that #29 was merged?
